### PR TITLE
Adding lint stage to molecule

### PR DESCRIPTION
**Pull request by domenicbove**
# Description

Hey @Fobhep can you review this one? Molecule runs from the roles/confluent.test directory it seems so pretty much does this command make sense:
```
  set -e
  yamllint -c ../../.yamllint ../..
```

As far as i can tell it works without errors and without your yamllint config file there are errors on line length

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

**Test Configuration**:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Fobhep** [comment]
@domenicbove thanks for the PR.
so the linting command per se looks good to me. 
I am not sure if I understand it correct that you are currently only testing three of your molecule scenarios?
Or am I missing something here?

**Comment by domenicbove** [comment]
Are you asking about the Jenkinsfile- and why there are only 3 scenarios in there? the reason it doesnt say `molecule test --all` is it really would take way too long and I haven't investigated parallelizing the tests. The tests still need to pass, I usually just run them manually

**Comment by Fobhep** [comment]
@domenicbove yeah exactly. 
but yes that makes absolutely sense to me - thanks :) I have a colleague that does Jenkins stuff, maybe I can ask him on occasion about parallel jobs in Jenkins.

**Comment by Fobhep** [comment]
I will merge this then

**Pull request merged**
